registered_models:
  - vae-square

processing_queues:
  vae-square: 
    atlas_create: vae_square_train

distributed:
  vae-square: 
    atlas_create: true

model_parameters:
  vae-square:
    atlas_create:
      num_epochs: 500
