registered_models:
  - resnet-atlas
  - dae-atlas

processing_queues:
  resnet-atlas: 
    grid.registered: resnet_atlas_infer
  dae-atlas:
    grid.registered: dae_atlas_init

distributed:
  resnet-atlas: 
    grid.registered: false
  dae-atlas:
    grid.registered: true

model_parameters:
  resnet-atlas:
    grid.registered:
      model_path: "/path/to/weights"
  dae-atlas:
    grid.registered:
      model_path: "/path/to/starting/weights"
